import 'dotenv/config';

export const PORT = process.env.PORT;

export const DATABASE_URL = process.env.DATABASE_URL;
export const DATABASE_REDIS = process.env.DATABASE_REDIS;

export const ELASTICSEARCH_URL = process.env.ELASTICSEARCH_URL;
export const ELASTICSEARCH_USERNAME = process.env.ELASTICSEARCH_USERNAME;
export const ELASTICSEARCH_PASSWORD = process.env.ELASTICSEARCH_PASSWORD;

export const RABBITMQ_URL = process.env.RABBITMQ_URL;

export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;

export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
export const GOOGLE_REDIRECT_URL = process.env.GOOGLE_REDIRECT_URL;

export const CLOUD_FOLDER_AVATAR = 'avatar';
export const CLOUD_FOLDER_LOCATION = 'locationImage';
export const CLOUD_FOLDER_ROOM = 'roomImage';

export const CLOUDINARY_NAME = process.env.CLOUDINARY_NAME;
export const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

export const ADMIN_EMAIL = process.env.ADMIN_EMAIL;
export const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;
console.log(
  '\n',
  {
    PORT: PORT,
    DATABASE_URL: DATABASE_URL,
    DATABASE_REDIS: DATABASE_REDIS,

    ELASTICSEARCH_URL: ELASTICSEARCH_URL,
    ELASTICSEARCH_USERNAME: ELASTICSEARCH_USERNAME,
    ELASTICSEARCH_PASSWORD: ELASTICSEARCH_PASSWORD,

    RABBITMQ_URL: RABBITMQ_URL,

    ACCESS_TOKEN_SECRET: ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET: REFRESH_TOKEN_SECRET,

    GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URL: GOOGLE_REDIRECT_URL,

    CLOUDINARY_NAME: CLOUDINARY_NAME,
    CLOUDINARY_API_KEY: CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: CLOUDINARY_API_SECRET,
    ADMIN_EMAIL: ADMIN_EMAIL,
    ADMIN_PASSWORD: ADMIN_PASSWORD,
  },
  '\n',
);
